"""auto-votes-final

Revision ID: d49ea32804ce
Revises: f78b74ea7ab9
Create Date: 2022-03-16 17:17:26.999771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49ea32804ce'
down_revision = 'f78b74ea7ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), server_default='TRUE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
